name: wavvec
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - torchaudio
  - pytorch
  - librosa
  - scikit-learn
  - matplotlib
  - pyyaml
  - pip
  - pip:
      - transformers==4.52.4
      - evaluate
      - pydub
      - soundfile
