name: bts_final_project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - librosa
  - joblib
  - pydantic
  - uvicorn
  - fastapi
  - pydub
  - httpx
  - aiofiles
  - python-multipart
  - ffmpeg
  - pip:
    - tensorflow
    - tensorflow-io
  - matplotlib
  - scipy
  - seaborn
  - requests
  - tqdm
  - python-dotenv
  - pip:
      - absl-py==2.2.2
      - kapre==0.3.7
      - moviepy==2.1.2
      - msgpack==1.1.0
      - openl3==0.4.2
      - proglog==0.1.12
      - protobuf==5.29.4
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - torch==2.1.0
      - tzdata==2025.2
